### ISSUE TITLE
cuda error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by tdrminglin** [kijai/ComfyUI-CogVideoXWrapper#122]
I updated the CogVideoXWrapper about 10 hours ago. after this update it keep showing this error when the workflow comes to Cogvideo Decode. I tried i2v and the Pose workflow, they both showed the same error. the error is only shown on the cmd window, and the Cogvideo Decode node is stuck since then.  the  full log is as follows:
got prompt
Temporal tiling disabled
Exception in thread Thread-22 (prompt_worker):
Traceback (most recent call last):
  File "I:\stable_diffusion\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "I:\stable_diffusion\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "I:\stable_diffusion\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "I:\stable_diffusion\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "I:\stable_diffusion\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 926, in decode
    frames = vae.decode(latents).sample
  File "I:\stable_diffusion\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\diffusers\utils\accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
  File "I:\stable_diffusion\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\diffusers\models\autoencoders\autoencoder_kl_cogvideox.py", line 1184, in decode
    decoded = self._decode(z).sample
  File "I:\stable_diffusion\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\diffusers\models\autoencoders\autoencoder_kl_cogvideox.py", line 1142, in _decode
    return self.tiled_decode(z, return_dict=return_dict)

  File "I:\stable_diffusion\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\diffusers\models\autoencoders\autoencoder_kl_cogvideox.py", line 1332, in tiled_decode
    tile = self.decoder(tile)
  File "I:\stable_diffusion\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "I:\stable_diffusion\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "I:\stable_diffusion\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\diffusers\models\autoencoders\autoencoder_kl_cogvideox.py", line 877, in forward
    hidden_states = up_block(hidden_states, temb, sample)
  File "I:\stable_diffusion\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "I:\stable_diffusion\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "I:\stable_diffusion\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\diffusers\models\autoencoders\autoencoder_kl_cogvideox.py", line 602, in forward
    hidden_states = resnet(hidden_states, temb, zq)
  File "I:\stable_diffusion\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "I:\stable_diffusion\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "I:\stable_diffusion\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\diffusers\models\autoencoders\autoencoder_kl_cogvideox.py", line 303, in forward
    hidden_states = self.conv2(hidden_states)
  File "I:\stable_diffusion\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "I:\stable_diffusion\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "I:\stable_diffusion\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\diffusers\models\autoencoders\autoencoder_kl_cogvideox.py", line 144, in forward
    output = self.conv(inputs)

  File "I:\stable_diffusion\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "I:\stable_diffusion\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "I:\stable_diffusion\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\diffusers\models\autoencoders\autoencoder_kl_cogvideox.py", line 64, in forward
    return super().forward(input)
  File "I:\stable_diffusion\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\torch\nn\modules\conv.py", line 610, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "I:\stable_diffusion\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\torch\nn\modules\conv.py", line 605, in _conv_forward
    return F.conv3d(
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "I:\stable_diffusion\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "<enhanced_experience vendors.sentry_sdk.integrations.threading>", line 99, in run
  File "<enhanced_experience vendors.sentry_sdk.integrations.threading>", line 94, in _run_old_run_func
  File "<enhanced_experience vendors.sentry_sdk.utils>", line 1649, in reraise
  File "<enhanced_experience vendors.sentry_sdk.integrations.threading>", line 92, in _run_old_run_func
  File "I:\stable_diffusion\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "I:\stable_diffusion\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\main.py", line 125, in prompt_worker
    e.execute(item[2], prompt_id, item[3], item[4])
  File "I:\stable_diffusion\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\custom_nodes\rgthree-comfy\__init__.py", line 211, in rgthree_execute
    return self.rgthree_old_execute(*args, **kwargs)
  File "I:\stable_diffusion\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\execution.py", line 494, in execute
    result, error, ex = execute(self.server, dynamic_prompt, self.caches, node_id, extra_data, executed, prompt_id, execution_list, pending_subgraph_results)
  File "I:\stable_diffusion\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\execution.py", line 384, in execute
    input_data_formatted[name] = [format_value(x) for x in inputs]
  File "I:\stable_diffusion\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\execution.py", line 384, in <listcomp>
    input_data_formatted[name] = [format_value(x) for x in inputs]
  File "I:\stable_diffusion\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\execution.py", line 236, in format_value
    return str(x)
  File "I:\stable_diffusion\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\torch\_tensor.py", line 461, in __repr__
    return torch._tensor_str._str(self, tensor_contents=tensor_contents)
  File "I:\stable_diffusion\ComfyUI-aki-v1.2\ComfyUI-aki-v1.2\python\lib\site-packages\torch\_tensor_str.py", line 677, in _str
------------------------
Fault Traceback: 
Not Available

**Comment by kijai** [comment]
Is this with vae_tiling enabled or not?

**Comment by tdrminglin** [comment]
> Is this with vae_tiling enabled or not?

Thanks for replying. vae_tiling is enabled.

**Comment by kijai** [comment]
> > Is this with vae_tiling enabled or not?
> 
> Thanks for replying. vae_tiling is enabled.

I don't really know the cause for that error, but if it worked before then try disabling the auto_tile_size as that's what I changed.

**Comment by tdrminglin** [comment]
1.I deleted "vae._clear_fake_context_parallel_cache()" 
2. replaced the vae_tiling  codes by those from the last version 
3. changed tiling settings to last version
I don't know which step worked, but  the error is gone. Thanks again.
