### ISSUE TITLE
Error when running fastmode

### ISSUE THREAD

**Issue by jpgallegoar** [kijai/ComfyUI-CogVideoXWrapper#136]
When I try activating fastmode, I get the error CUDA error: 

CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasLtMatmulAlgoGetHeuristic( ltHandle, computeDesc.descriptor(), Adesc.descriptor(), Bdesc.descriptor(), Cdesc.descriptor(), Ddesc.descriptor(), preference.descriptor(), 1, &heuristicResult, &returnedResult)`.

I suspect my CUDA version is not correct, I have v11.8. Which one do I need?

RTX 4090, Windows 11.

**Comment by kijai** [comment]
You need torch that's compiled for cuda 124.

**Comment by jpgallegoar** [comment]
> You need torch that's compiled for cuda 124.

Thank you, that worked.
